/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "app.h"

std::string Lighthouse::Greeter::greeting() {
    return std::string("Hello, World!");
}

int main () {
    Lighthouse::Greeter greeter;
    std::cout << greeter.greeting() << std::endl;
    std::cout << "ddd" << std::endl;

    return 0;
}
